/**
 * Ghost Billing — génération PDF facture (client / prévisualisation).
 * Données légales : companyConfig. Taxes : quebecInvoiceTax.
 */

import { jsPDF } from 'jspdf';
import { COMPANY_CONFIG } from '../config/companyConfig';
import { computeQuebecTaxes, formatCadAmount, type QuebecTaxBreakdown } from '../lib/quebecInvoiceTax';

export interface InvoiceLineItem {
  description: string;
  subtotalCad: number;
}

export interface InvoicePdfInput {
  invoiceNumber: string;
  issuedAt: Date;
  billToName: string;
  billToEmail?: string;
  lineItems: InvoiceLineItem[];
  locale?: 'fr' | 'en';
}

function aggregateLines(lineItems: InvoiceLineItem[]): QuebecTaxBreakdown {
  const subtotal = lineItems.reduce((sum, line) => sum + line.subtotalCad, 0);
  return computeQuebecTaxes(subtotal);
}

/**
 * Génère un PDF facture et déclenche le téléchargement dans le navigateur.
 */
export function downloadInvoicePdf(input: InvoicePdfInput): void {
  const locale = input.locale ?? 'fr';
  const taxes = aggregateLines(input.lineItems);
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const L = locale === 'fr';
  let y = 18;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(COMPANY_CONFIG.name, 20, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(COMPANY_CONFIG.address, 20, y);
  y += 5;
  doc.text(COMPANY_CONFIG.email, 20, y);
  y += 5;
  doc.text(`NEQ : ${COMPANY_CONFIG.neq}`, 20, y);
  y += 5;
  doc.text(`TPS : ${COMPANY_CONFIG.tpsNumber}`, 20, y);
  y += 5;
  doc.text(`TVQ : ${COMPANY_CONFIG.tvqNumber}`, 20, y);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(L ? 'FACTURE' : 'INVOICE', 150, 18);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`${L ? 'No' : 'No.'} ${input.invoiceNumber}`, 150, 26);
  doc.text(
    `${L ? 'Date' : 'Date'} : ${input.issuedAt.toLocaleDateString(L ? 'fr-CA' : 'en-CA')}`,
    150,
    32
  );

  y = 52;
  doc.setFont('helvetica', 'bold');
  doc.text(L ? 'Facturé à' : 'Bill to', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.text(input.billToName, 20, y);
  if (input.billToEmail) {
    y += 5;
    doc.text(input.billToEmail, 20, y);
  }

  y += 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text(L ? 'Description' : 'Description', 20, y);
  doc.text(L ? 'Montant' : 'Amount', 165, y, { align: 'right' });
  y += 2;
  doc.line(20, y, 195, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  for (const line of input.lineItems) {
    doc.text(line.description, 20, y);
    doc.text(formatCadAmount(line.subtotalCad, locale), 195, y, { align: 'right' });
    y += 7;
  }

  y += 4;
  doc.line(120, y, 195, y);
  y += 8;

  const rows: [string, string][] = [
    [L ? 'Sous-total' : 'Subtotal', formatCadAmount(taxes.subtotalCad, locale)],
    [L ? 'TPS (5 %)' : 'GST (5%)', formatCadAmount(taxes.tpsCad, locale)],
    [L ? 'TVQ (9,975 %)' : 'QST (9.975%)', formatCadAmount(taxes.tvqCad, locale)],
  ];
  for (const [label, value] of rows) {
    doc.text(label, 120, y);
    doc.text(value, 195, y, { align: 'right' });
    y += 6;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  y += 2;
  doc.text(L ? 'TOTAL' : 'TOTAL', 120, y);
  doc.text(formatCadAmount(taxes.totalCad, locale), 195, y, { align: 'right' });

  y += 14;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.text(
    L
      ? 'Facture générée par Primexpert (Ghost Billing). Numéros légaux provisoires.'
      : 'Invoice generated by Primexpert (Ghost Billing). Provisional legal numbers.',
    20,
    y
  );

  doc.save(`primexpert-facture-${input.invoiceNumber}.pdf`);
}

/** Exemple démo : forfait mensuel 175 $ (total ~201,21 $). */
export function downloadSampleMonthlyInvoice(billToName: string, billToEmail?: string): void {
  downloadInvoicePdf({
    invoiceNumber: `PX-${Date.now().toString(36).toUpperCase()}`,
    issuedAt: new Date(),
    billToName,
    billToEmail,
    lineItems: [{ description: 'Abonnement Primexpert — Solo (mensuel)', subtotalCad: 175 }],
    locale: 'fr',
  });
}
