/**
 * Questionnaire Déclaration du Vendeur RPA — sections D1 à D25.
 * Généré depuis Copilote dvRpaMapping.js (238 champs).
 * Regénérer : node scripts/generate-declaration-questionnaire.mjs
 */

import type { DeclarationSectionDef } from './types';

export const DECLARATION_SECTION_COUNT = 25;

export const DECLARATION_SECTIONS: DeclarationSectionDef[] = [
  {
    id: 'D1',
    titleFr: 'IDENTIFICATION DE L\'IMMEUBLE',
    titleEn: 'IDENTIFICATION DE L\'IMMEUBLE',
    category: 'standard',
    questions: [
      {
        id: 'Texte1',
        firestorePath: 'vendorDeclaration.dateDeclaration',
        labelFr: 'Date de la déclaration',
        labelEn: 'Date de la déclaration',
        fieldType: 'date',
      },
      {
        id: 'Texte2',
        firestorePath: 'adresse',
        labelFr: 'Adresse civique complète',
        labelEn: 'Adresse civique complète',
        fieldType: 'text',
      },
      {
        id: 'Texte3',
        firestorePath: 'municipalite',
        labelFr: 'Municipalité',
        labelEn: 'Municipalité',
        fieldType: 'text',
      },
      {
        id: 'Texte4',
        firestorePath: 'codePostal',
        labelFr: 'Code postal',
        labelEn: 'Code postal',
        fieldType: 'text',
      },
      {
        id: 'Texte5',
        firestorePath: 'vendorDeclaration.designationCadastrale',
        labelFr: 'Numéro(s) de la désignation cadastrale',
        labelEn: 'Numéro(s) de la désignation cadastrale',
        fieldType: 'text',
      },
    ],
  },
  {
    id: 'D2',
    titleFr: 'INFORMATIONS GÉNÉRALES',
    titleEn: 'INFORMATIONS GÉNÉRALES',
    category: 'standard',
    questions: [
      {
        id: 'Texte6',
        firestorePath: 'vendorDeclaration.d2.anneeAcquisition',
        labelFr: 'En quelle année avez-vous acquis l\'immeuble?',
        labelEn: 'En quelle année avez-vous acquis l\'immeuble?',
        fieldType: 'year',
        subSection: 'D2.1',
      },
      {
        id: 'Texte7',
        firestorePath: 'anneeConstruction',
        labelFr: 'Quelle est l\'année de construction approximative de l\'immeuble?',
        labelEn: 'Quelle est l\'année de construction approximative de l\'immeuble?',
        fieldType: 'year',
        subSection: 'D2.2',
      },
      {
        id: 'D2_3_question',
        firestorePath: 'vendorDeclaration.d2.hypotheques',
        labelFr: 'À votre connaissance, existe-t-il sur l\'immeuble des hypothèques, servitudes, droits de passage, empiètements, ou autres charges particulières?',
        labelEn: 'À votre connaissance, existe-t-il sur l\'immeuble des hypothèques, servitudes, droits de passage, empiètements, ou autres charges particulières?',
        fieldType: 'yesno',
        subSection: 'D2.3',
      },
      {
        id: 'Texte8',
        firestorePath: 'vendorDeclaration.d2.hypothequesDetails',
        labelFr: 'Si oui, donner les détails',
        labelEn: 'Si oui, donner les détails',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D2.3',
      },
      {
        id: 'D2_4_question',
        firestorePath: 'vendorDeclaration.d2.limitations',
        labelFr: 'Certaines limitations particulières s\'appliquent-elles à l\'immeuble (zone inondable, zone agricole, zone à risque de mouvement de terrain, règlements d\'urbanisme particuliers, etc.)?',
        labelEn: 'Certaines limitations particulières s\'appliquent-elles à l\'immeuble (zone inondable, zone agricole, zone à risque de mouvement de terrain, règlements d\'urbanisme particuliers, etc.)?',
        fieldType: 'yesno',
        subSection: 'D2.4',
      },
      {
        id: 'Texte9',
        firestorePath: 'vendorDeclaration.d2.limitationsDetails',
        labelFr: 'Si oui, préciser',
        labelEn: 'Si oui, préciser',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D2.4',
      },
      {
        id: 'D2_5_question',
        firestorePath: 'vendorDeclaration.d2.modifications',
        labelFr: 'Depuis votre acquisition, des modifications significatives ont-elles été apportées (ajout de bâtiments, clôtures, galerie, terrasses, cabanon, piscines, stationnement, etc.)?',
        labelEn: 'Depuis votre acquisition, des modifications significatives ont-elles été apportées (ajout de bâtiments, clôtures, galerie, terrasses, cabanon, piscines, stationnement, etc.)?',
        fieldType: 'yesno',
        subSection: 'D2.5',
      },
      {
        id: 'Texte10',
        firestorePath: 'vendorDeclaration.d2.modificationsDetails',
        labelFr: 'Si oui, indiquer les principaux travaux et l\'année approximative',
        labelEn: 'Si oui, indiquer les principaux travaux et l\'année approximative',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D2.5',
      },
      {
        id: 'D2_6_question',
        firestorePath: 'vendorDeclaration.d2.avisNonConformite',
        labelFr: 'Avez-vous déjà reçu un avis de non-conformité ou de correction d\'une compagnie d\'assurance, de la municipalité ou d\'un autre organisme relativement à l\'immeuble?',
        labelEn: 'Avez-vous déjà reçu un avis de non-conformité ou de correction d\'une compagnie d\'assurance, de la municipalité ou d\'un autre organisme relativement à l\'immeuble?',
        fieldType: 'yesno',
        subSection: 'D2.6',
      },
      {
        id: 'D2_7_question',
        firestorePath: 'vendorDeclaration.d2.refusAssurance',
        labelFr: 'Une compagnie d\'assurance a-t-elle déjà refusé d\'assurer l\'immeuble, ou l\'a assuré avec des exclusions ou une surprime particulière?',
        labelEn: 'Une compagnie d\'assurance a-t-elle déjà refusé d\'assurer l\'immeuble, ou l\'a assuré avec des exclusions ou une surprime particulière?',
        fieldType: 'yesno',
        subSection: 'D2.7',
      },
      {
        id: 'D2_8_question',
        firestorePath: 'vendorDeclaration.d2.reclamationAssureur',
        labelFr: 'Depuis votre acquisition, l\'immeuble a-t-il déjà fait l\'objet d\'une réclamation importante auprès d\'un assureur (dégâts d\'eau, feu, vent, verglas, autre sinistre)?',
        labelEn: 'Depuis votre acquisition, l\'immeuble a-t-il déjà fait l\'objet d\'une réclamation importante auprès d\'un assureur (dégâts d\'eau, feu, vent, verglas, autre sinistre)?',
        fieldType: 'yesno',
        subSection: 'D2.8',
      },
      {
        id: 'Texte11',
        firestorePath: 'vendorDeclaration.d2.reclamationDetails',
        labelFr: 'Si oui, décrire brièvement les événements',
        labelEn: 'Si oui, décrire brièvement les événements',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D2.8',
      },
    ],
  },
  {
    id: 'D3',
    titleFr: 'TERRAIN (SOL)',
    titleEn: 'TERRAIN (SOL)',
    category: 'standard',
    questions: [
      {
        id: 'D3_1_question',
        firestorePath: 'vendorDeclaration.d3.problemesSol',
        labelFr: 'Des problèmes de sol ont-ils déjà affecté l\'immeuble (affaissement, glissement, instabilité, mouvement de terrain, etc.)?',
        labelEn: 'Des problèmes de sol ont-ils déjà affecté l\'immeuble (affaissement, glissement, instabilité, mouvement de terrain, etc.)?',
        fieldType: 'yesno',
        subSection: 'D3.1',
      },
      {
        id: 'D3_2_question',
        firestorePath: 'vendorDeclaration.d3.travauxStabilisation',
        labelFr: 'Des travaux de stabilisation ou de correction du sol ou des fondations ont-ils déjà été réalisés?',
        labelEn: 'Des travaux de stabilisation ou de correction du sol ou des fondations ont-ils déjà été réalisés?',
        fieldType: 'yesno',
        subSection: 'D3.2',
      },
      {
        id: 'Texte12',
        firestorePath: 'vendorDeclaration.d3.travauxStabilisationDetails',
        labelFr: 'Si oui, quels travaux et à quelle époque?',
        labelEn: 'Si oui, quels travaux et à quelle époque?',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D3.2',
      },
      {
        id: 'D3_3_question',
        firestorePath: 'vendorDeclaration.d3.reservoirMazout',
        labelFr: 'Y a-t-il déjà eu un réservoir de mazout (en surface ou enfoui) sur le terrain?',
        labelEn: 'Y a-t-il déjà eu un réservoir de mazout (en surface ou enfoui) sur le terrain?',
        fieldType: 'yesno',
        subSection: 'D3.3',
      },
      {
        id: 'D3_4_question',
        firestorePath: 'vendorDeclaration.d3.deversement',
        labelFr: 'Y a-t-il déjà eu déversement ou fuite d\'un produit dans le sol pouvant l\'avoir contaminé (mazout, huile, plomb, autres)?',
        labelEn: 'Y a-t-il déjà eu déversement ou fuite d\'un produit dans le sol pouvant l\'avoir contaminé (mazout, huile, plomb, autres)?',
        fieldType: 'yesno',
        subSection: 'D3.4',
      },
      {
        id: 'Texte13',
        firestorePath: 'vendorDeclaration.d3.deversementDetails',
        labelFr: 'Si oui, préciser le produit, l\'année approximative et les correctifs apportés',
        labelEn: 'Si oui, préciser le produit, l\'année approximative et les correctifs apportés',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D3.4',
      },
      {
        id: 'D3_5_question',
        firestorePath: 'vendorDeclaration.d3.travauxTerrassement',
        labelFr: 'Des travaux majeurs de terrassement ou de remblai ont-ils été effectués?',
        labelEn: 'Des travaux majeurs de terrassement ou de remblai ont-ils été effectués?',
        fieldType: 'yesno',
        subSection: 'D3.5',
      },
      {
        id: 'D3_6_question',
        firestorePath: 'vendorDeclaration.d3.accumulationEau',
        labelFr: 'De l\'eau s\'accumule-t-elle périodiquement sur le terrain ou dans le stationnement?',
        labelEn: 'De l\'eau s\'accumule-t-elle périodiquement sur le terrain ou dans le stationnement?',
        fieldType: 'yesno',
        subSection: 'D3.6',
      },
      {
        id: 'D3_7_question',
        firestorePath: 'vendorDeclaration.d3.eauJaunatre',
        labelFr: 'Avez-vous déjà observé de l\'eau jaunâtre ou rougeâtre sur le terrain ou dans le fossé?',
        labelEn: 'Avez-vous déjà observé de l\'eau jaunâtre ou rougeâtre sur le terrain ou dans le fossé?',
        fieldType: 'yesno',
        subSection: 'D3.7',
      },
      {
        id: 'D3_8_question',
        firestorePath: 'vendorDeclaration.d3.depotOcre',
        labelFr: 'Y a-t-il un dépôt d\'ocre dans le sol ou dans le drain français?',
        labelEn: 'Y a-t-il un dépôt d\'ocre dans le sol ou dans le drain français?',
        fieldType: 'yesno',
        subSection: 'D3.8',
      },
      {
        id: 'D3_9_question',
        firestorePath: 'vendorDeclaration.d3.ancienDepotoir',
        labelFr: 'Avez-vous connaissance d\'informations indiquant que l\'immeuble est situé sur un ancien dépotoir ou sur un site d\'enfouissement?',
        labelEn: 'Avez-vous connaissance d\'informations indiquant que l\'immeuble est situé sur un ancien dépotoir ou sur un site d\'enfouissement?',
        fieldType: 'yesno',
        subSection: 'D3.9',
      },
    ],
  },
  {
    id: 'D4',
    titleFr: 'DOMMAGES CAUSÉS PAR L\'EAU',
    titleEn: 'DOMMAGES CAUSÉS PAR L\'EAU',
    category: 'standard',
    questions: [
      {
        id: 'D4_1_question',
        firestorePath: 'vendorDeclaration.d4.infiltrations',
        labelFr: 'Est-ce qu\'il y a déjà eu des infiltrations d\'eau dans l\'immeuble?',
        labelEn: 'Est-ce qu\'il y a déjà eu des infiltrations d\'eau dans l\'immeuble?',
        fieldType: 'yesno',
        subSection: 'D4.1',
      },
      {
        id: 'Texte14',
        firestorePath: 'vendorDeclaration.d4.infiltrationsDetails',
        labelFr: 'Si oui, à quels endroits (toiture, murs, fenêtres, sous-sol, vide sanitaire, etc.) et en quelle année',
        labelEn: 'Si oui, à quels endroits (toiture, murs, fenêtres, sous-sol, vide sanitaire, etc.) et en quelle année',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D4.1',
      },
      {
        id: 'D4_2_question',
        firestorePath: 'vendorDeclaration.d4.fuite',
        labelFr: 'Une fuite d\'eau a-t-elle déjà causé des dommages importants (lave-vaisselle, laveuse, chauffe-eau, toilettes, douche, bain, autres)?',
        labelEn: 'Une fuite d\'eau a-t-elle déjà causé des dommages importants (lave-vaisselle, laveuse, chauffe-eau, toilettes, douche, bain, autres)?',
        fieldType: 'yesno',
        subSection: 'D4.2',
      },
      {
        id: 'Texte15',
        firestorePath: 'vendorDeclaration.d4.fuiteDetails',
        labelFr: 'Si oui, décrire brièvement',
        labelEn: 'Si oui, décrire brièvement',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D4.2',
      },
    ],
  },
  {
    id: 'D5',
    titleFr: 'SOUS-SOL ET FONDATIONS',
    titleEn: 'SOUS-SOL ET FONDATIONS',
    category: 'standard',
    questions: [
      {
        id: 'D5_1_question',
        firestorePath: 'vendorDeclaration.d5.typeFondation',
        labelFr: 'Quel est le type de fondation principal?',
        labelEn: 'Quel est le type de fondation principal?',
        fieldType: 'checkbox_group',
        subSection: 'D5.1',
      },
      {
        id: 'Texte17',
        firestorePath: 'vendorDeclaration.d5.fondationAutre',
        labelFr: 'Autre type de fondation (préciser)',
        labelEn: 'Autre type de fondation (préciser)',
        fieldType: 'text',
        subSection: 'D5.1',
      },
      {
        id: 'D5_2_question',
        firestorePath: 'vendorDeclaration.d5.problemes',
        labelFr: 'Des problèmes ont-ils déjà affecté le sous-sol ou le vide sanitaire (fissures, humidité, infiltration, moisissure, odeurs, soulèvement de la dalle, etc.)?',
        labelEn: 'Des problèmes ont-ils déjà affecté le sous-sol ou le vide sanitaire (fissures, humidité, infiltration, moisissure, odeurs, soulèvement de la dalle, etc.)?',
        fieldType: 'yesno',
        subSection: 'D5.2',
      },
      {
        id: 'Texte16',
        firestorePath: 'vendorDeclaration.d5.problemesDetails',
        labelFr: 'Si oui, préciser',
        labelEn: 'Si oui, préciser',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D5.2',
      },
      {
        id: 'D5_3_question',
        firestorePath: 'vendorDeclaration.d5.deversement',
        labelFr: 'Y a-t-il déjà eu déversement d\'un produit au sous-sol ou dans le vide sanitaire (mazout, huile, mercure, autres)?',
        labelEn: 'Y a-t-il déjà eu déversement d\'un produit au sous-sol ou dans le vide sanitaire (mazout, huile, mercure, autres)?',
        fieldType: 'yesno',
        subSection: 'D5.3',
      },
    ],
  },
  {
    id: 'D6',
    titleFr: 'ANIMAUX INDÉSIRABLES',
    titleEn: 'ANIMAUX INDÉSIRABLES',
    category: 'standard',
    questions: [
      {
        id: 'D6_1_question',
        firestorePath: 'vendorDeclaration.d6.animaux',
        labelFr: 'Est-ce qu\'il y a déjà eu présence d\'insectes ou d\'animaux indésirables à l\'intérieur de l\'immeuble (fourmis charpentières, rongeurs, punaises de lit, chauves-souris, etc.)?',
        labelEn: 'Est-ce qu\'il y a déjà eu présence d\'insectes ou d\'animaux indésirables à l\'intérieur de l\'immeuble (fourmis charpentières, rongeurs, punaises de lit, chauves-souris, etc.)?',
        fieldType: 'yesno',
        subSection: 'D6.1',
      },
      {
        id: 'Texte18',
        firestorePath: 'vendorDeclaration.d6.animauxDetails',
        labelFr: 'Si oui, lesquels et à quelle période approximative?',
        labelEn: 'Si oui, lesquels et à quelle période approximative?',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D6.1',
      },
      {
        id: 'D6_2_question',
        firestorePath: 'vendorDeclaration.d6.exterminateur',
        labelFr: 'Avez-vous déjà eu recours à un exterminateur professionnel pour ces problèmes?',
        labelEn: 'Avez-vous déjà eu recours à un exterminateur professionnel pour ces problèmes?',
        fieldType: 'yesno',
        subSection: 'D6.2',
      },
    ],
  },
  {
    id: 'D7',
    titleFr: 'QUALITÉ DE L\'AIR INTÉRIEUR',
    titleEn: 'QUALITÉ DE L\'AIR INTÉRIEUR',
    category: 'standard',
    questions: [
      {
        id: 'D7_1_question',
        firestorePath: 'vendorDeclaration.d7.condensation',
        labelFr: 'De la condensation importante s\'est-elle déjà formée en hiver à certains endroits (fenêtres, murs, plafond, etc.)?',
        labelEn: 'De la condensation importante s\'est-elle déjà formée en hiver à certains endroits (fenêtres, murs, plafond, etc.)?',
        fieldType: 'yesno',
        subSection: 'D7.1',
      },
      {
        id: 'D7_2_question',
        firestorePath: 'vendorDeclaration.d7.odeurs',
        labelFr: 'Avez-vous déjà constaté des odeurs nauséabondes ou persistantes (égout, humidité, mazout, gaz, autre)?',
        labelEn: 'Avez-vous déjà constaté des odeurs nauséabondes ou persistantes (égout, humidité, mazout, gaz, autre)?',
        fieldType: 'yesno',
        subSection: 'D7.2',
      },
      {
        id: 'D7_3_question',
        firestorePath: 'vendorDeclaration.d7.moisissure',
        labelFr: 'Avez-vous déjà observé des traces de moisissure, de pourriture ou de champignons?',
        labelEn: 'Avez-vous déjà observé des traces de moisissure, de pourriture ou de champignons?',
        fieldType: 'yesno',
        subSection: 'D7.3',
      },
      {
        id: 'Texte19',
        firestorePath: 'vendorDeclaration.d7.moisissureDetails',
        labelFr: 'Si oui, à quels endroits et quelles mesures ont été prises?',
        labelEn: 'Si oui, à quels endroits et quelles mesures ont été prises?',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D7.3',
      },
      {
        id: 'D7_4_question',
        firestorePath: 'vendorDeclaration.d7.amiante',
        labelFr: 'Des matériaux pouvant contenir de l\'amiante (vermiculite, tuiles, plafonds, calorifuges, etc.) ont-ils été utilisés dans l\'immeuble?',
        labelEn: 'Des matériaux pouvant contenir de l\'amiante (vermiculite, tuiles, plafonds, calorifuges, etc.) ont-ils été utilisés dans l\'immeuble?',
        fieldType: 'yesno_nsp',
        subSection: 'D7.4',
      },
    ],
  },
  {
    id: 'D8',
    titleFr: 'TOITURE',
    titleEn: 'TOITURE',
    category: 'standard',
    questions: [
      {
        id: 'Texte20',
        firestorePath: 'vendorDeclaration.d8.typeRevetement',
        labelFr: 'Quel est le type de revêtement de la toiture principale (bardeaux d\'asphalte, tôle, membrane, autre)?',
        labelEn: 'Quel est le type de revêtement de la toiture principale (bardeaux d\'asphalte, tôle, membrane, autre)?',
        fieldType: 'text',
        subSection: 'D8.1',
      },
      {
        id: 'Texte21',
        firestorePath: 'vendorDeclaration.d8.anneeRevetement',
        labelFr: 'À quelle année remonte l\'installation ou le dernier remplacement connu du revêtement de toiture?',
        labelEn: 'À quelle année remonte l\'installation ou le dernier remplacement connu du revêtement de toiture?',
        fieldType: 'year',
        subSection: 'D8.2',
      },
      {
        id: 'D8_3_question',
        firestorePath: 'vendorDeclaration.d8.documentsToiture',
        labelFr: 'Avez-vous des documents ou factures attestant des travaux de toiture?',
        labelEn: 'Avez-vous des documents ou factures attestant des travaux de toiture?',
        fieldType: 'yesno',
        subSection: 'D8.3',
      },
      {
        id: 'D8_4_question',
        firestorePath: 'vendorDeclaration.d8.entretienToiture',
        labelFr: 'La toiture nécessite-t-elle un entretien régulier particulier (déglaçage, nettoyage, etc.)?',
        labelEn: 'La toiture nécessite-t-elle un entretien régulier particulier (déglaçage, nettoyage, etc.)?',
        fieldType: 'yesno',
        subSection: 'D8.4',
      },
      {
        id: 'D8_5_question',
        firestorePath: 'vendorDeclaration.d8.typeIsolant',
        labelFr: 'Quel est le type d\'isolant dans l\'entretoit (si connu)?',
        labelEn: 'Quel est le type d\'isolant dans l\'entretoit (si connu)?',
        fieldType: 'checkbox_group',
        subSection: 'D8.5',
      },
      {
        id: 'Texte22_isolant',
        firestorePath: 'vendorDeclaration.d8.isolantAutre',
        labelFr: 'Autre type d\'isolant',
        labelEn: 'Autre type d\'isolant',
        fieldType: 'text',
        subSection: 'D8.5',
      },
      {
        id: 'D8_6_question',
        firestorePath: 'vendorDeclaration.d8.glace',
        labelFr: 'De la glace ou des glaçons se forment-ils régulièrement en bordure de toit?',
        labelEn: 'De la glace ou des glaçons se forment-ils régulièrement en bordure de toit?',
        fieldType: 'yesno',
        subSection: 'D8.6',
      },
    ],
  },
  {
    id: 'D9',
    titleFr: 'PLOMBERIE ET DRAINAGE',
    titleEn: 'PLOMBERIE ET DRAINAGE',
    category: 'standard',
    questions: [
      {
        id: 'D9_1_question',
        firestorePath: 'vendorDeclaration.d9.problemesPlomberie',
        labelFr: 'Avez-vous déjà eu des problèmes liés à la plomberie (fuites, pression irrégulière, eau trouble, rouille, bruit anormal, odeurs, mauvaise évacuation, refoulement, etc.)?',
        labelEn: 'Avez-vous déjà eu des problèmes liés à la plomberie (fuites, pression irrégulière, eau trouble, rouille, bruit anormal, odeurs, mauvaise évacuation, refoulement, etc.)?',
        fieldType: 'yesno',
        subSection: 'D9.1',
      },
      {
        id: 'D9_2_question',
        firestorePath: 'vendorDeclaration.d9.puisard',
        labelFr: 'L\'immeuble est-il équipé d\'un puisard ou d\'une fosse de rétention d\'eau?',
        labelEn: 'L\'immeuble est-il équipé d\'un puisard ou d\'une fosse de rétention d\'eau?',
        fieldType: 'yesno',
        subSection: 'D9.2',
      },
      {
        id: 'D9_3_question',
        firestorePath: 'vendorDeclaration.d9.pompe',
        labelFr: 'L\'immeuble est-il équipé d\'une pompe d\'évacuation (sump pump)?',
        labelEn: 'L\'immeuble est-il équipé d\'une pompe d\'évacuation (sump pump)?',
        fieldType: 'yesno',
        subSection: 'D9.3',
      },
      {
        id: 'Texte23',
        firestorePath: 'vendorDeclaration.d9.pompeAnnee',
        labelFr: 'Si oui, en quelle année environ a-t-elle été installée?',
        labelEn: 'Si oui, en quelle année environ a-t-elle été installée?',
        fieldType: 'year',
        optional: true,
        subSection: 'D9.3',
      },
      {
        id: 'D9_4_question',
        firestorePath: 'vendorDeclaration.d9.drainFrancais',
        labelFr: 'L\'immeuble est-il équipé d\'un drain français?',
        labelEn: 'L\'immeuble est-il équipé d\'un drain français?',
        fieldType: 'yesno_nsp',
        subSection: 'D9.4',
      },
      {
        id: 'D9_5_question',
        firestorePath: 'vendorDeclaration.d9.renvoisModifies',
        labelFr: 'Les renvois de plomberie ou le drainage de la fondation ont-ils déjà été modifiés?',
        labelEn: 'Les renvois de plomberie ou le drainage de la fondation ont-ils déjà été modifiés?',
        fieldType: 'yesno',
        subSection: 'D9.5',
      },
      {
        id: 'Texte24',
        firestorePath: 'vendorDeclaration.d9.anneeChauffeEau',
        labelFr: 'Quelle est l\'année d\'installation approximative du chauffe-eau?',
        labelEn: 'Quelle est l\'année d\'installation approximative du chauffe-eau?',
        fieldType: 'year',
        subSection: 'D9.6',
      },
      {
        id: 'Texte25',
        firestorePath: 'vendorDeclaration.d9.capaciteChauffeEau',
        labelFr: 'Capacité du chauffe-eau (litres)',
        labelEn: 'Capacité du chauffe-eau (litres)',
        fieldType: 'number',
        subSection: 'D9.6',
      },
      {
        id: 'D9_7_question',
        firestorePath: 'vendorDeclaration.d9.adoucisseur',
        labelFr: 'L\'immeuble est-il équipé d\'un adoucisseur d\'eau ou d\'un système de filtration?',
        labelEn: 'L\'immeuble est-il équipé d\'un adoucisseur d\'eau ou d\'un système de filtration?',
        fieldType: 'yesno',
        subSection: 'D9.7',
      },
      {
        id: 'D9_8_question',
        firestorePath: 'vendorDeclaration.d9.aqueducMunicipal',
        labelFr: 'L\'immeuble est-il desservi par les services d\'aqueduc de la municipalité?',
        labelEn: 'L\'immeuble est-il desservi par les services d\'aqueduc de la municipalité?',
        fieldType: 'yesno',
        subSection: 'D9.8',
      },
      {
        id: 'Texte26',
        firestorePath: 'vendorDeclaration.d9.typeAlimentationEau',
        labelFr: 'Préciser le type d\'alimentation en eau (puits artésien, puits de surface, captage de source, autre)',
        labelEn: 'Préciser le type d\'alimentation en eau (puits artésien, puits de surface, captage de source, autre)',
        fieldType: 'text',
        optional: true,
        subSection: 'D9.8',
      },
      {
        id: 'D9_9_question',
        firestorePath: 'vendorDeclaration.d9.egoutMunicipal',
        labelFr: 'L\'immeuble est-il raccordé au réseau d\'égout municipal?',
        labelEn: 'L\'immeuble est-il raccordé au réseau d\'égout municipal?',
        fieldType: 'yesno',
        subSection: 'D9.9',
      },
      {
        id: 'Texte27',
        firestorePath: 'vendorDeclaration.d9.typeEvacuation',
        labelFr: 'Préciser le type de système d\'évacuation des eaux usées (fosse septique, champs d\'épuration, etc.)',
        labelEn: 'Préciser le type de système d\'évacuation des eaux usées (fosse septique, champs d\'épuration, etc.)',
        fieldType: 'text',
        optional: true,
        subSection: 'D9.9',
      },
      {
        id: 'D9_10_question',
        firestorePath: 'vendorDeclaration.d9.problemesEvacuation',
        labelFr: 'Des problèmes d\'évacuation des eaux usées (odeurs, débordements, avis de non-conformité) ont-ils déjà été constatés?',
        labelEn: 'Des problèmes d\'évacuation des eaux usées (odeurs, débordements, avis de non-conformité) ont-ils déjà été constatés?',
        fieldType: 'yesno',
        subSection: 'D9.10',
      },
      {
        id: 'D9_11_question',
        firestorePath: 'vendorDeclaration.d9.clapetAntiretour',
        labelFr: 'L\'immeuble est-il équipé d\'un clapet antiretour pour prévenir les refoulements d\'égout?',
        labelEn: 'L\'immeuble est-il équipé d\'un clapet antiretour pour prévenir les refoulements d\'égout?',
        fieldType: 'yesno_nsp',
        subSection: 'D9.11',
      },
    ],
  },
  {
    id: 'D10',
    titleFr: 'ÉNERGIE',
    titleEn: 'ÉNERGIE',
    category: 'standard',
    questions: [
      {
        id: 'D10_1_question',
        firestorePath: 'vendorDeclaration.d10.electricite',
        labelFr: 'L\'immeuble est-il desservi par les services d\'électricité?',
        labelEn: 'L\'immeuble est-il desservi par les services d\'électricité?',
        fieldType: 'yesno',
        subSection: 'D10.1',
      },
      {
        id: 'D10_2_question',
        firestorePath: 'vendorDeclaration.d10.problemesElectricite',
        labelFr: 'Y a-t-il déjà eu des problèmes liés à l\'électricité (disjoncteur qui saute régulièrement, lumières qui clignotent, surcharge, etc.)?',
        labelEn: 'Y a-t-il déjà eu des problèmes liés à l\'électricité (disjoncteur qui saute régulièrement, lumières qui clignotent, surcharge, etc.)?',
        fieldType: 'yesno',
        subSection: 'D10.2',
      },
      {
        id: 'D10_3_question',
        firestorePath: 'vendorDeclaration.d10.gaz',
        labelFr: 'L\'immeuble est-il desservi par un service de gaz naturel ou au propane?',
        labelEn: 'L\'immeuble est-il desservi par un service de gaz naturel ou au propane?',
        fieldType: 'yesno',
        subSection: 'D10.3',
      },
      {
        id: 'Texte28',
        firestorePath: 'vendorDeclaration.d10.gazAppareils',
        labelFr: 'Si oui, indiquer les appareils alimentés (fournaise, cuisinière, foyer, chauffe-eau, etc.)',
        labelEn: 'Si oui, indiquer les appareils alimentés (fournaise, cuisinière, foyer, chauffe-eau, etc.)',
        fieldType: 'text',
        optional: true,
        subSection: 'D10.3',
      },
      {
        id: 'D10_4_question',
        firestorePath: 'vendorDeclaration.d10.generatrice',
        labelFr: 'L\'immeuble est-il équipé d\'une génératrice intégrée?',
        labelEn: 'L\'immeuble est-il équipé d\'une génératrice intégrée?',
        fieldType: 'yesno',
        subSection: 'D10.4',
      },
      {
        id: 'D10_5_question',
        firestorePath: 'vendorDeclaration.d10.borneVE',
        labelFr: 'L\'immeuble est-il équipé d\'une borne de recharge pour véhicule électrique?',
        labelEn: 'L\'immeuble est-il équipé d\'une borne de recharge pour véhicule électrique?',
        fieldType: 'yesno',
        subSection: 'D10.5',
      },
      {
        id: 'D10_6_question',
        firestorePath: 'vendorDeclaration.d10.efficaciteEnergetique',
        labelFr: 'Des systèmes améliorant l\'efficacité énergétique (thermopompe, panneaux solaires, autres) sont-ils en place?',
        labelEn: 'Des systèmes améliorant l\'efficacité énergétique (thermopompe, panneaux solaires, autres) sont-ils en place?',
        fieldType: 'yesno',
        subSection: 'D10.6',
      },
      {
        id: 'D10_7_question',
        firestorePath: 'vendorDeclaration.d10.certificationEnergetique',
        labelFr: 'L\'immeuble a-t-il déjà fait l\'objet d\'une certification d\'efficacité énergétique (Novoclimat, Maison verte, LEED, autre)?',
        labelEn: 'L\'immeuble a-t-il déjà fait l\'objet d\'une certification d\'efficacité énergétique (Novoclimat, Maison verte, LEED, autre)?',
        fieldType: 'yesno',
        subSection: 'D10.7',
      },
    ],
  },
  {
    id: 'D11',
    titleFr: 'TÉLÉCOMMUNICATION',
    titleEn: 'TÉLÉCOMMUNICATION',
    category: 'standard',
    questions: [
      {
        id: 'D11_1_question',
        firestorePath: 'vendorDeclaration.d11.servicesDisponibles',
        labelFr: 'Quels services de télécommunication sont disponibles dans le secteur de l\'immeuble?',
        labelEn: 'Quels services de télécommunication sont disponibles dans le secteur de l\'immeuble?',
        fieldType: 'checkbox_group',
        subSection: 'D11.1',
      },
      {
        id: 'Texte29',
        firestorePath: 'vendorDeclaration.d11.autreService',
        labelFr: 'Autre service de télécommunication',
        labelEn: 'Autre service de télécommunication',
        fieldType: 'text',
        subSection: 'D11.1',
      },
      {
        id: 'D11_2_question',
        firestorePath: 'vendorDeclaration.d11.relie',
        labelFr: 'L\'immeuble est-il relié à un ou plusieurs de ces services?',
        labelEn: 'L\'immeuble est-il relié à un ou plusieurs de ces services?',
        fieldType: 'yesno',
        subSection: 'D11.2',
      },
    ],
  },
  {
    id: 'D12',
    titleFr: 'CHAUFFAGE, CLIMATISATION ET VENTILATION',
    titleEn: 'CHAUFFAGE, CLIMATISATION ET VENTILATION',
    category: 'standard',
    questions: [
      {
        id: 'D12_1_question',
        firestorePath: 'vendorDeclaration.d12.sourceChauffage',
        labelFr: 'Quelle est la principale source d\'énergie utilisée pour le chauffage?',
        labelEn: 'Quelle est la principale source d\'énergie utilisée pour le chauffage?',
        fieldType: 'checkbox_group',
        subSection: 'D12.1',
      },
      {
        id: 'Texte30',
        firestorePath: 'vendorDeclaration.d12.sourceAutre',
        labelFr: 'Autre source de chauffage',
        labelEn: 'Autre source de chauffage',
        fieldType: 'text',
        subSection: 'D12.1',
      },
      {
        id: 'Texte31',
        firestorePath: 'vendorDeclaration.d12.descriptionSysteme',
        labelFr: 'Le système de chauffage comprend-il une fournaise, des plinthes électriques, un système central, un plancher chauffant, ou autre? Décrire brièvement',
        labelEn: 'Le système de chauffage comprend-il une fournaise, des plinthes électriques, un système central, un plancher chauffant, ou autre? Décrire brièvement',
        fieldType: 'textarea',
        subSection: 'D12.2',
      },
      {
        id: 'D12_3_question',
        firestorePath: 'vendorDeclaration.d12.chauffageAppoint',
        labelFr: 'L\'immeuble est-il équipé d\'un système de chauffage d\'appoint (poêle, foyer, poêle au granule, etc.)?',
        labelEn: 'L\'immeuble est-il équipé d\'un système de chauffage d\'appoint (poêle, foyer, poêle au granule, etc.)?',
        fieldType: 'yesno',
        subSection: 'D12.3',
      },
      {
        id: 'D12_4_question',
        firestorePath: 'vendorDeclaration.d12.cheminee',
        labelFr: 'L\'immeuble est-il pourvu d\'une cheminée?',
        labelEn: 'L\'immeuble est-il pourvu d\'une cheminée?',
        fieldType: 'yesno',
        subSection: 'D12.4',
      },
      {
        id: 'D12_4_documents',
        firestorePath: 'vendorDeclaration.d12.documentsCheminee',
        labelFr: 'Si oui, avez-vous des documents attestant des caractéristiques et de l\'année d\'installation de la cheminée?',
        labelEn: 'Si oui, avez-vous des documents attestant des caractéristiques et de l\'année d\'installation de la cheminée?',
        fieldType: 'yesno',
        optional: true,
        subSection: 'D12.4',
      },
      {
        id: 'D12_5_question',
        firestorePath: 'vendorDeclaration.d12.thermopompe',
        labelFr: 'L\'immeuble est-il équipé d\'une thermopompe (chauffage et climatisation)?',
        labelEn: 'L\'immeuble est-il équipé d\'une thermopompe (chauffage et climatisation)?',
        fieldType: 'yesno',
        subSection: 'D12.5',
      },
      {
        id: 'D12_6_question',
        firestorePath: 'vendorDeclaration.d12.climatisation',
        labelFr: 'L\'immeuble est-il équipé d\'un système de climatisation permanente (murale ou centrale)?',
        labelEn: 'L\'immeuble est-il équipé d\'un système de climatisation permanente (murale ou centrale)?',
        fieldType: 'yesno',
        subSection: 'D12.6',
      },
      {
        id: 'D12_7_question',
        firestorePath: 'vendorDeclaration.d12.echangeurAir',
        labelFr: 'L\'immeuble est-il équipé d\'un échangeur d\'air?',
        labelEn: 'L\'immeuble est-il équipé d\'un échangeur d\'air?',
        fieldType: 'yesno',
        subSection: 'D12.7',
      },
      {
        id: 'Texte32',
        firestorePath: 'vendorDeclaration.d12.echangeurDetails',
        labelFr: 'Si oui, savez-vous à quelle année remonte son installation et faites-vous effectuer un entretien périodique?',
        labelEn: 'Si oui, savez-vous à quelle année remonte son installation et faites-vous effectuer un entretien périodique?',
        fieldType: 'text',
        optional: true,
        subSection: 'D12.7',
      },
    ],
  },
  {
    id: 'D13',
    titleFr: 'RAPPORTS D\'INSPECTION ET AUTRES EXPERTISES',
    titleEn: 'RAPPORTS D\'INSPECTION ET AUTRES EXPERTISES',
    category: 'standard',
    questions: [
      {
        id: 'D13_1_question',
        firestorePath: 'vendorDeclaration.d13.inspection',
        labelFr: 'L\'immeuble a-t-il déjà fait l\'objet d\'une inspection par un professionnel (inspection préachat, inspection en bâtiment, etc.)?',
        labelEn: 'L\'immeuble a-t-il déjà fait l\'objet d\'une inspection par un professionnel (inspection préachat, inspection en bâtiment, etc.)?',
        fieldType: 'yesno',
        subSection: 'D13.1',
      },
      {
        id: 'D13_1_fournir',
        firestorePath: 'vendorDeclaration.d13.fournirRapports',
        labelFr: 'Si oui, êtes-vous en mesure de fournir copie des rapports à l\'acheteur?',
        labelEn: 'Si oui, êtes-vous en mesure de fournir copie des rapports à l\'acheteur?',
        fieldType: 'yesno',
        optional: true,
        subSection: 'D13.1',
      },
      {
        id: 'D13_2_question',
        firestorePath: 'vendorDeclaration.d13.testsSpecialises',
        labelFr: 'Des tests ou expertises spécialisés ont-ils déjà été effectués (pyrite, radon, amiante, qualité de l\'air, qualité de l\'eau, analyse de sol, autres)?',
        labelEn: 'Des tests ou expertises spécialisés ont-ils déjà été effectués (pyrite, radon, amiante, qualité de l\'air, qualité de l\'eau, analyse de sol, autres)?',
        fieldType: 'yesno',
        subSection: 'D13.2',
      },
      {
        id: 'Texte33',
        firestorePath: 'vendorDeclaration.d13.testsDetails',
        labelFr: 'Si oui, résumer les tests réalisés et les résultats généraux',
        labelEn: 'Si oui, résumer les tests réalisés et les résultats généraux',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D13.2',
      },
    ],
  },
  {
    id: 'D14',
    titleFr: 'AUTRES INFORMATIONS',
    titleEn: 'AUTRES INFORMATIONS',
    category: 'standard',
    questions: [
      {
        id: 'D14_1_question',
        firestorePath: 'vendorDeclaration.d14.dommagesSinistres',
        labelFr: 'L\'immeuble a-t-il déjà subi des dommages attribuables à des événements comme le verglas, le vent, les inondations, un incendie, ou tout autre sinistre important?',
        labelEn: 'L\'immeuble a-t-il déjà subi des dommages attribuables à des événements comme le verglas, le vent, les inondations, un incendie, ou tout autre sinistre important?',
        fieldType: 'yesno',
        subSection: 'D14.1',
      },
      {
        id: 'D14_2_question',
        firestorePath: 'vendorDeclaration.d14.evenementsSecurite',
        labelFr: 'Des événements particuliers liés à la sécurité ou à l\'ordre public (ex. production de drogues, chambre de culture, activités criminelles, etc.) se sont-ils déjà produits dans l\'immeuble?',
        labelEn: 'Des événements particuliers liés à la sécurité ou à l\'ordre public (ex. production de drogues, chambre de culture, activités criminelles, etc.) se sont-ils déjà produits dans l\'immeuble?',
        fieldType: 'yesno',
        subSection: 'D14.2',
      },
      {
        id: 'D14_3_question',
        firestorePath: 'vendorDeclaration.d14.suicideViolence',
        labelFr: 'Un suicide ou un acte de violence grave a-t-il déjà eu lieu dans l\'immeuble?',
        labelEn: 'Un suicide ou un acte de violence grave a-t-il déjà eu lieu dans l\'immeuble?',
        fieldType: 'yesno',
        subSection: 'D14.3',
      },
      {
        id: 'D14_4_question',
        firestorePath: 'vendorDeclaration.d14.travauxNonMentionnes',
        labelFr: 'D\'autres travaux majeurs non mentionnés précédemment ont-ils été effectués (modification de la division des pièces, changement de revêtement de plancher, réaménagement intérieur, etc.)?',
        labelEn: 'D\'autres travaux majeurs non mentionnés précédemment ont-ils été effectués (modification de la division des pièces, changement de revêtement de plancher, réaménagement intérieur, etc.)?',
        fieldType: 'yesno',
        subSection: 'D14.4',
      },
      {
        id: 'Texte34',
        firestorePath: 'vendorDeclaration.d14.travauxDetails',
        labelFr: 'Si oui, les décrire sommairement',
        labelEn: 'Si oui, les décrire sommairement',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D14.4',
      },
      {
        id: 'Texte35',
        firestorePath: 'vendorDeclaration.d14.autresElements',
        labelFr: 'Tout autre élément dont vous avez connaissance et qui pourrait avoir un impact sur la valeur, l\'usage ou l\'attrait de l\'immeuble doit être indiqué ici',
        labelEn: 'Tout autre élément dont vous avez connaissance et qui pourrait avoir un impact sur la valeur, l\'usage ou l\'attrait de l\'immeuble doit être indiqué ici',
        fieldType: 'textarea',
        subSection: 'D14.5',
      },
      {
        id: 'Texte36',
        firestorePath: 'vendorDeclaration.d14.champsReserve36',
        labelFr: 'Champ réservé',
        labelEn: 'Champ réservé',
        fieldType: 'text',
        optional: true,
        subSection: 'D14.6',
      },
    ],
  },
  {
    id: 'D15',
    titleFr: 'SECTION SPÉCIFIQUE AUX RÉSIDENCES PRIVÉES POUR AÎNÉS (RPA)',
    titleEn: 'SECTION SPÉCIFIQUE AUX RÉSIDENCES PRIVÉES POUR AÎNÉS (RPA)',
    category: 'rpa',
    questions: [
      {
        id: 'Texte37',
        firestorePath: 'nom',
        labelFr: 'Nom commercial / Nom d\'usage de la résidence',
        labelEn: 'Nom commercial / Nom d\'usage de la résidence',
        fieldType: 'text',
        subSection: 'D15.1',
      },
      {
        id: 'Texte38',
        firestorePath: 'vendorDeclaration.d15.raisonSociale',
        labelFr: 'Raison sociale de l\'entreprise exploitante',
        labelEn: 'Raison sociale de l\'entreprise exploitante',
        fieldType: 'text',
        subSection: 'D15.2',
      },
      {
        id: 'Texte39',
        firestorePath: 'vendorDeclaration.d15.neq',
        labelFr: 'NEQ',
        labelEn: 'NEQ',
        fieldType: 'text',
        subSection: 'D15.2',
      },
      {
        id: 'D15_2_formeJuridique',
        firestorePath: 'vendorDeclaration.d15.formeJuridique',
        labelFr: 'Forme juridique',
        labelEn: 'Forme juridique',
        fieldType: 'checkbox_group',
        subSection: 'D15.2',
      },
      {
        id: 'Texte40',
        firestorePath: 'vendorDeclaration.d15.formeJuridiqueAutre',
        labelFr: 'Autre forme juridique (préciser)',
        labelEn: 'Autre forme juridique (préciser)',
        fieldType: 'text',
        subSection: 'D15.2',
      },
      {
        id: 'Texte41',
        firestorePath: 'vendorDeclaration.d15.proprietaire1Nom',
        labelFr: 'Nom du propriétaire 1 (actions/parts)',
        labelEn: 'Nom du propriétaire 1 (actions/parts)',
        fieldType: 'text',
        subSection: 'D15.3',
      },
      {
        id: 'Texte42',
        firestorePath: 'vendorDeclaration.d15.proprietaire1Pourcent',
        labelFr: 'Pourcentage détenu',
        labelEn: 'Pourcentage détenu',
        fieldType: 'percent',
        subSection: 'D15.3',
      },
      {
        id: 'Texte43',
        firestorePath: 'vendorDeclaration.d15.proprietaire2Nom',
        labelFr: 'Nom du propriétaire 2 (actions/parts)',
        labelEn: 'Nom du propriétaire 2 (actions/parts)',
        fieldType: 'text',
        subSection: 'D15.3',
      },
      {
        id: 'Texte44',
        firestorePath: 'vendorDeclaration.d15.proprietaire2Pourcent',
        labelFr: 'Pourcentage détenu',
        labelEn: 'Pourcentage détenu',
        fieldType: 'percent',
        subSection: 'D15.3',
      },
      {
        id: 'Texte45',
        firestorePath: 'vendorDeclaration.d15.proprietaire3Nom',
        labelFr: 'Nom du propriétaire 3 (actions/parts)',
        labelEn: 'Nom du propriétaire 3 (actions/parts)',
        fieldType: 'text',
        subSection: 'D15.3',
      },
      {
        id: 'Texte46',
        firestorePath: 'vendorDeclaration.d15.proprietaire3Pourcent',
        labelFr: 'Pourcentage détenu',
        labelEn: 'Pourcentage détenu',
        fieldType: 'percent',
        subSection: 'D15.3',
      },
      {
        id: 'Texte47',
        firestorePath: 'vendorDeclaration.d15.anneeProprietaireImmeuble',
        labelFr: 'Depuis quelle année êtes-vous propriétaire de l\'immeuble?',
        labelEn: 'Depuis quelle année êtes-vous propriétaire de l\'immeuble?',
        fieldType: 'year',
        subSection: 'D15.4a',
      },
      {
        id: 'Texte48',
        firestorePath: 'vendorDeclaration.d15.anneeProprietaireEntreprise',
        labelFr: 'Depuis quelle année êtes-vous propriétaire de l\'entreprise exploitante?',
        labelEn: 'Depuis quelle année êtes-vous propriétaire de l\'entreprise exploitante?',
        fieldType: 'year',
        subSection: 'D15.4b',
      },
      {
        id: 'Texte49',
        firestorePath: 'vendorDeclaration.d15.anneeExploitationRPA',
        labelFr: 'Depuis quelle année l\'exploitation RPA sur ce site?',
        labelEn: 'Depuis quelle année l\'exploitation RPA sur ce site?',
        fieldType: 'year',
        subSection: 'D15.4c',
      },
      {
        id: 'D15_5_categories',
        firestorePath: 'vendorDeclaration.d15.categoriesClientele',
        labelFr: 'Catégories de clientèle accueillies',
        labelEn: 'Catégories de clientèle accueillies',
        fieldType: 'checkbox_group',
        subSection: 'D15.5',
      },
      {
        id: 'Texte50',
        firestorePath: 'vendorDeclaration.d15.categoriesAutre',
        labelFr: 'Autre catégorie (préciser)',
        labelEn: 'Autre catégorie (préciser)',
        fieldType: 'text',
        subSection: 'D15.5',
      },
      {
        id: 'Texte51',
        firestorePath: 'vendorDeclaration.d15.placesAutorisees',
        labelFr: 'Nombre de places autorisées par la certification RPA',
        labelEn: 'Nombre de places autorisées par la certification RPA',
        fieldType: 'number',
        subSection: 'D15.6',
      },
      {
        id: 'Texte52',
        firestorePath: 'nombreUnites',
        labelFr: 'Nombre d\'unités physiques',
        labelEn: 'Nombre d\'unités physiques',
        fieldType: 'number',
        subSection: 'D15.6',
      },
    ],
  },
  {
    id: 'D16',
    titleFr: 'IMMEUBLE, SITE ET ZONAGE',
    titleEn: 'IMMEUBLE, SITE ET ZONAGE',
    category: 'rpa',
    questions: [
      {
        id: 'Texte53',
        firestorePath: 'vendorDeclaration.d16.superficieTerrain',
        labelFr: 'Superficie approximative du terrain',
        labelEn: 'Superficie approximative du terrain',
        fieldType: 'text',
        subSection: 'D16.1',
      },
      {
        id: 'Texte54',
        firestorePath: 'vendorDeclaration.d16.superficiePlancher',
        labelFr: 'Superficie brute de plancher',
        labelEn: 'Superficie brute de plancher',
        fieldType: 'text',
        subSection: 'D16.1',
      },
      {
        id: 'Texte55',
        firestorePath: 'nombreEtages',
        labelFr: 'Nombre d\'étages',
        labelEn: 'Nombre d\'étages',
        fieldType: 'number',
        subSection: 'D16.2',
      },
      {
        id: 'D16_2_sousSol',
        firestorePath: 'vendorDeclaration.d16.sousSol',
        labelFr: 'Sous-sol',
        labelEn: 'Sous-sol',
        fieldType: 'yesno',
        subSection: 'D16.2',
      },
      {
        id: 'D16_3_question',
        firestorePath: 'vendorDeclaration.d16.ensembleImmobilier',
        labelFr: 'L\'immeuble fait-il partie d\'un ensemble immobilier (plusieurs bâtiments sur un même site)?',
        labelEn: 'L\'immeuble fait-il partie d\'un ensemble immobilier (plusieurs bâtiments sur un même site)?',
        fieldType: 'yesno',
        subSection: 'D16.3',
      },
      {
        id: 'Texte56',
        firestorePath: 'vendorDeclaration.d16.ensembleDetails',
        labelFr: 'Si oui, préciser la composition (nombre de bâtiments, liens fonctionnels)',
        labelEn: 'Si oui, préciser la composition (nombre de bâtiments, liens fonctionnels)',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D16.3',
      },
      {
        id: 'D16_4_question',
        firestorePath: 'vendorDeclaration.d16.zonageAutoriseRPA',
        labelFr: 'Le zonage autorise-t-il explicitement l\'usage RPA?',
        labelEn: 'Le zonage autorise-t-il explicitement l\'usage RPA?',
        fieldType: 'yesno_nsp',
        subSection: 'D16.4',
      },
      {
        id: 'Texte57',
        firestorePath: 'vendorDeclaration.d16.numeroZone',
        labelFr: 'Numéro de zone / usage',
        labelEn: 'Numéro de zone / usage',
        fieldType: 'text',
        subSection: 'D16.4',
      },
      {
        id: 'Texte58',
        firestorePath: 'vendorDeclaration.d16.zonageInfos',
        labelFr: 'Informations connues sur le zonage',
        labelEn: 'Informations connues sur le zonage',
        fieldType: 'textarea',
        subSection: 'D16.4',
      },
      {
        id: 'D16_5_question',
        firestorePath: 'vendorDeclaration.d16.nonConformitesZonage',
        labelFr: 'Avez-vous connaissance de non-conformités de zonage (usage dérogatoire, droits acquis, etc.)?',
        labelEn: 'Avez-vous connaissance de non-conformités de zonage (usage dérogatoire, droits acquis, etc.)?',
        fieldType: 'yesno',
        subSection: 'D16.5',
      },
      {
        id: 'Texte59',
        firestorePath: 'vendorDeclaration.d16.nonConformitesDetails',
        labelFr: 'Si oui, détailler',
        labelEn: 'Si oui, détailler',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D16.5',
      },
      {
        id: 'D16_6_question',
        firestorePath: 'vendorDeclaration.d16.avisMunicipalite',
        labelFr: 'Avez-vous reçu un avis écrit de la municipalité concernant l\'usage, le zonage ou la conformité du bâtiment?',
        labelEn: 'Avez-vous reçu un avis écrit de la municipalité concernant l\'usage, le zonage ou la conformité du bâtiment?',
        fieldType: 'yesno',
        subSection: 'D16.6',
      },
    ],
  },
  {
    id: 'D17',
    titleFr: 'CERTIFICATION RPA, PERMIS ET AVIS DES AUTORITÉS',
    titleEn: 'CERTIFICATION RPA, PERMIS ET AVIS DES AUTORITÉS',
    category: 'rpa',
    questions: [
      {
        id: 'D17_1_question',
        firestorePath: 'vendorDeclaration.d17.certifieeRPA',
        labelFr: 'La résidence est-elle actuellement certifiée comme RPA par le MSSS?',
        labelEn: 'La résidence est-elle actuellement certifiée comme RPA par le MSSS?',
        fieldType: 'yesno',
        subSection: 'D17.1',
      },
      {
        id: 'Texte60',
        firestorePath: 'numeroCertification',
        labelFr: 'Numéro de certification',
        labelEn: 'Numéro de certification',
        fieldType: 'text',
        subSection: 'D17.1',
      },
      {
        id: 'Texte61',
        firestorePath: 'dateCertification',
        labelFr: 'Date d\'échéance de la certification',
        labelEn: 'Date d\'échéance de la certification',
        fieldType: 'date',
        subSection: 'D17.1',
      },
      {
        id: 'Texte62',
        firestorePath: 'vendorDeclaration.d17.dateDerniereVisite',
        labelFr: 'Date de la dernière visite d\'évaluation/certification',
        labelEn: 'Date de la dernière visite d\'évaluation/certification',
        fieldType: 'date',
        subSection: 'D17.2',
      },
      {
        id: 'D17_3_question',
        firestorePath: 'vendorDeclaration.d17.avisNonConformiteMSSS',
        labelFr: 'Avez-vous déjà reçu un ou plusieurs avis de non-conformité du MSSS?',
        labelEn: 'Avez-vous déjà reçu un ou plusieurs avis de non-conformité du MSSS?',
        fieldType: 'yesno',
        subSection: 'D17.3',
      },
      {
        id: 'Texte63',
        firestorePath: 'vendorDeclaration.d17.avisNonConformiteDetails',
        labelFr: 'Si oui, pour chaque avis, indiquer: année, nature des non-conformités et statut des correctifs',
        labelEn: 'Si oui, pour chaque avis, indiquer: année, nature des non-conformités et statut des correctifs',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D17.3',
      },
      {
        id: 'D17_4a_question',
        firestorePath: 'vendorDeclaration.d17.avisIncendie',
        labelFr: 'Avis, constats ou ordonnances reçus du Service d\'incendie / prévention incendie?',
        labelEn: 'Avis, constats ou ordonnances reçus du Service d\'incendie / prévention incendie?',
        fieldType: 'yesno',
        subSection: 'D17.4a',
      },
      {
        id: 'Texte64',
        firestorePath: 'vendorDeclaration.d17.avisIncendieAnnees',
        labelFr: 'Année(s)',
        labelEn: 'Année(s)',
        fieldType: 'text',
        optional: true,
        subSection: 'D17.4a',
      },
      {
        id: 'D17_4b_question',
        firestorePath: 'vendorDeclaration.d17.avisMAPAQ',
        labelFr: 'Avis reçus du MAPAQ (cuisine / services alimentaires)?',
        labelEn: 'Avis reçus du MAPAQ (cuisine / services alimentaires)?',
        fieldType: 'yesno',
        subSection: 'D17.4b',
      },
      {
        id: 'Texte65',
        firestorePath: 'vendorDeclaration.d17.avisMAPAQAnnees',
        labelFr: 'Année(s)',
        labelEn: 'Année(s)',
        fieldType: 'text',
        optional: true,
        subSection: 'D17.4b',
      },
      {
        id: 'D17_4c_question',
        firestorePath: 'vendorDeclaration.d17.avisCNESST',
        labelFr: 'Avis reçus de la CNESST?',
        labelEn: 'Avis reçus de la CNESST?',
        fieldType: 'yesno',
        subSection: 'D17.4c',
      },
      {
        id: 'Texte66',
        firestorePath: 'vendorDeclaration.d17.avisCNESSTAnnees',
        labelFr: 'Année(s)',
        labelEn: 'Année(s)',
        fieldType: 'text',
        optional: true,
        subSection: 'D17.4c',
      },
      {
        id: 'D17_4d_question',
        firestorePath: 'vendorDeclaration.d17.avisRegie',
        labelFr: 'Avis reçus de la Régie du bâtiment / inspection municipale?',
        labelEn: 'Avis reçus de la Régie du bâtiment / inspection municipale?',
        fieldType: 'yesno',
        subSection: 'D17.4d',
      },
      {
        id: 'Texte67',
        firestorePath: 'vendorDeclaration.d17.avisRegieAnnees',
        labelFr: 'Année(s)',
        labelEn: 'Année(s)',
        fieldType: 'text',
        optional: true,
        subSection: 'D17.4d',
      },
      {
        id: 'D17_4e_question',
        firestorePath: 'vendorDeclaration.d17.avisAutreOrganisme',
        labelFr: 'Avis reçus d\'un autre organisme (CIUSSS, OIIQ, etc.)?',
        labelEn: 'Avis reçus d\'un autre organisme (CIUSSS, OIIQ, etc.)?',
        fieldType: 'yesno',
        subSection: 'D17.4e',
      },
      {
        id: 'Texte68',
        firestorePath: 'vendorDeclaration.d17.avisAutrePreciser',
        labelFr: 'Préciser l\'organisme et l\'année',
        labelEn: 'Préciser l\'organisme et l\'année',
        fieldType: 'text',
        optional: true,
        subSection: 'D17.4e',
      },
      {
        id: 'Texte69',
        firestorePath: 'vendorDeclaration.d17.correctifsDescription',
        labelFr: 'Pour tout « Oui », décrire les principaux éléments et le statut des correctifs',
        labelEn: 'Pour tout « Oui », décrire les principaux éléments et le statut des correctifs',
        fieldType: 'textarea',
        subSection: 'D17.4',
      },
    ],
  },
  {
    id: 'D18',
    titleFr: 'CARACTÉRISTIQUES PHYSIQUES ET TRAVAUX MAJEURS',
    titleEn: 'CARACTÉRISTIQUES PHYSIQUES ET TRAVAUX MAJEURS',
    category: 'rpa',
    questions: [
      {
        id: 'D18_1a_question',
        firestorePath: 'vendorDeclaration.d18.problemesStructure',
        labelFr: 'À votre connaissance, y a-t-il eu des problèmes de structure (affaissement, fissures majeures, renforcement de poutres, etc.)?',
        labelEn: 'À votre connaissance, y a-t-il eu des problèmes de structure (affaissement, fissures majeures, renforcement de poutres, etc.)?',
        fieldType: 'yesno',
        subSection: 'D18.1a',
      },
      {
        id: 'D18_1b_question',
        firestorePath: 'vendorDeclaration.d18.travauxStabilisation',
        labelFr: 'Travaux de stabilisation des fondations ou du sol?',
        labelEn: 'Travaux de stabilisation des fondations ou du sol?',
        fieldType: 'yesno',
        subSection: 'D18.1b',
      },
      {
        id: 'D18_1c_question',
        firestorePath: 'vendorDeclaration.d18.rapportsIngenieur',
        labelFr: 'Avis ou rapports d\'ingénieur sur la structure?',
        labelEn: 'Avis ou rapports d\'ingénieur sur la structure?',
        fieldType: 'yesno',
        subSection: 'D18.1c',
      },
      {
        id: 'Texte70',
        firestorePath: 'vendorDeclaration.d18.structureResume',
        labelFr: 'Si oui à l\'une des questions ci-dessus, donner un résumé et joindre les rapports',
        labelEn: 'Si oui à l\'une des questions ci-dessus, donner un résumé et joindre les rapports',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D18.1',
      },
      {
        id: 'Texte71',
        firestorePath: 'vendorDeclaration.d18.travauxToiture',
        labelFr: 'Toiture - travaux réalisés',
        labelEn: 'Toiture - travaux réalisés',
        fieldType: 'text',
        subSection: 'D18.2a',
      },
      {
        id: 'Texte72',
        firestorePath: 'vendorDeclaration.d18.travauxToitureAnnee',
        labelFr: 'Année',
        labelEn: 'Année',
        fieldType: 'year',
        subSection: 'D18.2a',
      },
      {
        id: 'Texte73',
        firestorePath: 'vendorDeclaration.d18.travauxToitureGarantie',
        labelFr: 'Garantie restante',
        labelEn: 'Garantie restante',
        fieldType: 'text',
        subSection: 'D18.2a',
      },
      {
        id: 'Texte74',
        firestorePath: 'vendorDeclaration.d18.travauxFenetres',
        labelFr: 'Fenêtres / portes - travaux réalisés',
        labelEn: 'Fenêtres / portes - travaux réalisés',
        fieldType: 'text',
        subSection: 'D18.2b',
      },
      {
        id: 'Texte75',
        firestorePath: 'vendorDeclaration.d18.travauxFenetresAnnee',
        labelFr: 'Année',
        labelEn: 'Année',
        fieldType: 'year',
        subSection: 'D18.2b',
      },
      {
        id: 'Texte76',
        firestorePath: 'vendorDeclaration.d18.travauxFenetresGarantie',
        labelFr: 'Garantie restante',
        labelEn: 'Garantie restante',
        fieldType: 'text',
        subSection: 'D18.2b',
      },
      {
        id: 'Texte77',
        firestorePath: 'vendorDeclaration.d18.travauxRevetements',
        labelFr: 'Revêtements extérieurs - travaux réalisés',
        labelEn: 'Revêtements extérieurs - travaux réalisés',
        fieldType: 'text',
        subSection: 'D18.2c',
      },
      {
        id: 'Texte78',
        firestorePath: 'vendorDeclaration.d18.travauxRevetementsAnnee',
        labelFr: 'Année',
        labelEn: 'Année',
        fieldType: 'year',
        subSection: 'D18.2c',
      },
      {
        id: 'Texte79',
        firestorePath: 'vendorDeclaration.d18.travauxMecaniques',
        labelFr: 'Systèmes mécaniques (chauffage, ventilation, climatisation)',
        labelEn: 'Systèmes mécaniques (chauffage, ventilation, climatisation)',
        fieldType: 'text',
        subSection: 'D18.2d',
      },
    ],
  },
  {
    id: 'D19',
    titleFr: 'SÉCURITÉ INCENDIE, URGENCE ET CONTINUITÉ DES SERVICES',
    titleEn: 'SÉCURITÉ INCENDIE, URGENCE ET CONTINUITÉ DES SERVICES',
    category: 'rpa',
    questions: [
      {
        id: 'D19_1_gicleurs',
        firestorePath: 'vendorDeclaration.d19.gicleursPresent',
        labelFr: 'Système de gicleurs automatique',
        labelEn: 'Système de gicleurs automatique',
        fieldType: 'checkbox_group',
        subSection: 'D19.1',
      },
      {
        id: 'Texte80',
        firestorePath: 'vendorDeclaration.d19.gicleursAnnee',
        labelFr: 'Année d\'installation',
        labelEn: 'Année d\'installation',
        fieldType: 'year',
        subSection: 'D19.1',
      },
      {
        id: 'Texte81',
        firestorePath: 'vendorDeclaration.d19.gicleursFournisseur',
        labelFr: 'Nom du fournisseur de service / entretien',
        labelEn: 'Nom du fournisseur de service / entretien',
        fieldType: 'text',
        subSection: 'D19.1',
      },
      {
        id: 'Texte82',
        firestorePath: 'vendorDeclaration.d19.gicleursDateInspection',
        labelFr: 'Date de la dernière inspection certifiée',
        labelEn: 'Date de la dernière inspection certifiée',
        fieldType: 'date',
        subSection: 'D19.1',
      },
      {
        id: 'D19_1_recommandations',
        firestorePath: 'vendorDeclaration.d19.gicleursRecommandations',
        labelFr: 'Recommandations en suspens dans le dernier rapport?',
        labelEn: 'Recommandations en suspens dans le dernier rapport?',
        fieldType: 'yesno',
        subSection: 'D19.1',
      },
      {
        id: 'Texte83',
        firestorePath: 'vendorDeclaration.d19.gicleursRecommandationsDetails',
        labelFr: 'Si oui, lesquelles?',
        labelEn: 'Si oui, lesquelles?',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D19.1',
      },
      {
        id: 'D19_2a_question',
        firestorePath: 'vendorDeclaration.d19.alarmeRelieCentrale',
        labelFr: 'Système d\'alarme incendie relié à une centrale externe 24/7?',
        labelEn: 'Système d\'alarme incendie relié à une centrale externe 24/7?',
        fieldType: 'yesno',
        subSection: 'D19.2a',
      },
      {
        id: 'D19_2b_question',
        firestorePath: 'vendorDeclaration.d19.detecteursFumee',
        labelFr: 'Détecteurs de fumée / chaleur dans les unités?',
        labelEn: 'Détecteurs de fumée / chaleur dans les unités?',
        fieldType: 'yesno',
        subSection: 'D19.2b',
      },
      {
        id: 'D19_2c_question',
        firestorePath: 'vendorDeclaration.d19.detecteursCO',
        labelFr: 'Détecteurs de CO (monoxyde de carbone)?',
        labelEn: 'Détecteurs de CO (monoxyde de carbone)?',
        fieldType: 'yesno',
        subSection: 'D19.2c',
      },
      {
        id: 'Texte84',
        firestorePath: 'vendorDeclaration.d19.alarmeDateEntretien',
        labelFr: 'Date du dernier entretien / test',
        labelEn: 'Date du dernier entretien / test',
        fieldType: 'date',
        subSection: 'D19.2',
      },
      {
        id: 'D19_3_question',
        firestorePath: 'vendorDeclaration.d19.plansEvacuation',
        labelFr: 'Plans d\'évacuation affichés à chaque étage?',
        labelEn: 'Plans d\'évacuation affichés à chaque étage?',
        fieldType: 'yesno',
        subSection: 'D19.3',
      },
      {
        id: 'D19_4_question',
        firestorePath: 'vendorDeclaration.d19.exercicesEvacuation',
        labelFr: 'Exercices d\'évacuation réalisés avec les résidents et le personnel?',
        labelEn: 'Exercices d\'évacuation réalisés avec les résidents et le personnel?',
        fieldType: 'yesno',
        subSection: 'D19.4',
      },
      {
        id: 'Texte85',
        firestorePath: 'vendorDeclaration.d19.exercicesFrequence',
        labelFr: 'Fréquence habituelle',
        labelEn: 'Fréquence habituelle',
        fieldType: 'text',
        subSection: 'D19.4',
      },
      {
        id: 'Texte86',
        firestorePath: 'vendorDeclaration.d19.exercicesDernierDate',
        labelFr: 'Date du dernier exercice',
        labelEn: 'Date du dernier exercice',
        fieldType: 'date',
        subSection: 'D19.4',
      },
      {
        id: 'D19_5_question',
        firestorePath: 'vendorDeclaration.d19.generatricePresente',
        labelFr: 'Génératrice d\'appoint présente?',
        labelEn: 'Génératrice d\'appoint présente?',
        fieldType: 'yesno',
        subSection: 'D19.5',
      },
      {
        id: 'D19_5_type',
        firestorePath: 'vendorDeclaration.d19.generatriceType',
        labelFr: 'Type de génératrice',
        labelEn: 'Type de génératrice',
        fieldType: 'checkbox_group',
        subSection: 'D19.5',
      },
      {
        id: 'Texte87',
        firestorePath: 'vendorDeclaration.d19.generatriceTypeAutre',
        labelFr: 'Autre type (préciser)',
        labelEn: 'Autre type (préciser)',
        fieldType: 'text',
        subSection: 'D19.5',
      },
      {
        id: 'Texte88',
        firestorePath: 'vendorDeclaration.d19.generatriceAnnee',
        labelFr: 'Année d\'installation',
        labelEn: 'Année d\'installation',
        fieldType: 'year',
        subSection: 'D19.5',
      },
      {
        id: 'Texte89',
        firestorePath: 'vendorDeclaration.d19.generatriceDateEntretien',
        labelFr: 'Date du dernier entretien',
        labelEn: 'Date du dernier entretien',
        fieldType: 'date',
        subSection: 'D19.5',
      },
      {
        id: 'Texte90',
        firestorePath: 'vendorDeclaration.d19.generatriceEquipements',
        labelFr: 'Équipements alimentés (ascenseurs, éclairage, cuisine, oxygène, etc.)',
        labelEn: 'Équipements alimentés (ascenseurs, éclairage, cuisine, oxygène, etc.)',
        fieldType: 'textarea',
        subSection: 'D19.5',
      },
    ],
  },
  {
    id: 'D20',
    titleFr: 'INSTALLATIONS, UNITÉS ET SERVICES AUX RÉSIDENTS',
    titleEn: 'INSTALLATIONS, UNITÉS ET SERVICES AUX RÉSIDENTS',
    category: 'rpa',
    questions: [
      {
        id: 'Texte91',
        firestorePath: 'vendorDeclaration.d20.chambresPartagees',
        labelFr: 'Chambres avec SDB partagée',
        labelEn: 'Chambres avec SDB partagée',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte92',
        firestorePath: 'vendorDeclaration.d20.chambresPrivees',
        labelFr: 'Chambres avec SDB privée',
        labelEn: 'Chambres avec SDB privée',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte93',
        firestorePath: 'vendorDeclaration.d20.studios',
        labelFr: 'Studios / 1½',
        labelEn: 'Studios / 1½',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte94',
        firestorePath: 'vendorDeclaration.d20.deuxEtDemi',
        labelFr: '2½',
        labelEn: '2½',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte95',
        firestorePath: 'vendorDeclaration.d20.troisEtDemi',
        labelFr: '3½',
        labelEn: '3½',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte96',
        firestorePath: 'vendorDeclaration.d20.quatreEtDemiPlus',
        labelFr: '4½ et plus',
        labelEn: '4½ et plus',
        fieldType: 'number',
        subSection: 'D20.1',
      },
      {
        id: 'Texte97',
        firestorePath: 'vendorDeclaration.d20.unitesAdaptees',
        labelFr: 'Nombre d\'unités adaptées (fauteuil roulant, SDB adaptée, portes élargies)',
        labelEn: 'Nombre d\'unités adaptées (fauteuil roulant, SDB adaptée, portes élargies)',
        fieldType: 'number',
        subSection: 'D20.2',
      },
      {
        id: 'D20_3_espaces',
        firestorePath: 'vendorDeclaration.d20.espacesCommuns',
        labelFr: 'Espaces communs présents',
        labelEn: 'Espaces communs présents',
        fieldType: 'checkbox_group',
        subSection: 'D20.3',
      },
      {
        id: 'D20_3_espaces2',
        firestorePath: 'vendorDeclaration.d20.espacesCommunsAutres',
        labelFr: 'Autres espaces communs',
        labelEn: 'Autres espaces communs',
        fieldType: 'checkbox_group',
        subSection: 'D20.3',
      },
      {
        id: 'Texte98',
        firestorePath: 'vendorDeclaration.d20.espacesAutrePreciser',
        labelFr: 'Autre espace (préciser)',
        labelEn: 'Autre espace (préciser)',
        fieldType: 'text',
        subSection: 'D20.3',
      },
      {
        id: 'D20_4_services',
        firestorePath: 'vendorDeclaration.d20.servicesInclus',
        labelFr: 'Services inclus dans l\'offre de base',
        labelEn: 'Services inclus dans l\'offre de base',
        fieldType: 'checkbox_group',
        subSection: 'D20.4',
      },
      {
        id: 'D20_4_services2',
        firestorePath: 'vendorDeclaration.d20.servicesInclusAutres',
        labelFr: 'Autres services inclus',
        labelEn: 'Autres services inclus',
        fieldType: 'checkbox_group',
        subSection: 'D20.4',
      },
      {
        id: 'Texte99',
        firestorePath: 'vendorDeclaration.d20.servicesAutrePreciser',
        labelFr: 'Autre service (préciser)',
        labelEn: 'Autre service (préciser)',
        fieldType: 'text',
        subSection: 'D20.4',
      },
      {
        id: 'D20_5_question',
        firestorePath: 'vendorDeclaration.d20.cuisineComplete',
        labelFr: 'Cuisine complète sur place?',
        labelEn: 'Cuisine complète sur place?',
        fieldType: 'yesno',
        subSection: 'D20.5',
      },
      {
        id: 'Texte100',
        firestorePath: 'vendorDeclaration.d20.cuisineDateMAPAQ',
        labelFr: 'Date de la dernière inspection MAPAQ',
        labelEn: 'Date de la dernière inspection MAPAQ',
        fieldType: 'date',
        subSection: 'D20.5',
      },
      {
        id: 'Texte101',
        firestorePath: 'vendorDeclaration.d20.cuisineAvisRecommandations',
        labelFr: 'Avis ou recommandations en cours',
        labelEn: 'Avis ou recommandations en cours',
        fieldType: 'textarea',
        subSection: 'D20.5',
      },
    ],
  },
  {
    id: 'D21',
    titleFr: 'OCCUPATION, CONTRATS ET CLIENTÈLE',
    titleEn: 'OCCUPATION, CONTRATS ET CLIENTÈLE',
    category: 'rpa',
    questions: [
      {
        id: 'Texte102',
        firestorePath: 'nombreUnites',
        labelFr: 'Nombre total d\'unités',
        labelEn: 'Nombre total d\'unités',
        fieldType: 'number',
        subSection: 'D21.1',
      },
      {
        id: 'Texte103',
        firestorePath: 'vendorDeclaration.d21.unitesOccupees',
        labelFr: 'Unités occupées',
        labelEn: 'Unités occupées',
        fieldType: 'number',
        subSection: 'D21.1',
      },
      {
        id: 'Texte104',
        firestorePath: 'vendorDeclaration.d21.unitesVacantes',
        labelFr: 'Unités vacantes',
        labelEn: 'Unités vacantes',
        fieldType: 'number',
        subSection: 'D21.1',
      },
      {
        id: 'Texte105',
        firestorePath: 'tauxOccupation',
        labelFr: 'Taux d\'occupation moyen des 12 derniers mois (approx.)',
        labelEn: 'Taux d\'occupation moyen des 12 derniers mois (approx.)',
        fieldType: 'percent',
        subSection: 'D21.1',
      },
      {
        id: 'Texte106',
        firestorePath: 'vendorDeclaration.d21.pourcentAutonomes',
        labelFr: 'Autonomes (%)',
        labelEn: 'Autonomes (%)',
        fieldType: 'percent',
        subSection: 'D21.2',
      },
      {
        id: 'Texte107',
        firestorePath: 'vendorDeclaration.d21.pourcentSemiAutonomes',
        labelFr: 'Semi-autonomes (%)',
        labelEn: 'Semi-autonomes (%)',
        fieldType: 'percent',
        subSection: 'D21.2',
      },
      {
        id: 'Texte108',
        firestorePath: 'vendorDeclaration.d21.pourcentPerteCognitive',
        labelFr: 'Perte cognitive légère (%)',
        labelEn: 'Perte cognitive légère (%)',
        fieldType: 'percent',
        subSection: 'D21.2',
      },
      {
        id: 'Texte109',
        firestorePath: 'vendorDeclaration.d21.autresProfils',
        labelFr: 'Autres profils significatifs',
        labelEn: 'Autres profils significatifs',
        fieldType: 'text',
        subSection: 'D21.2',
      },
      {
        id: 'D21_3_documents',
        firestorePath: 'vendorDeclaration.d21.typeDocuments',
        labelFr: 'Type de documents signés avec les résidents',
        labelEn: 'Type de documents signés avec les résidents',
        fieldType: 'checkbox_group',
        subSection: 'D21.3',
      },
      {
        id: 'Texte110',
        firestorePath: 'vendorDeclaration.d21.typeDocumentsAutre',
        labelFr: 'Autre type (préciser)',
        labelEn: 'Autre type (préciser)',
        fieldType: 'text',
        subSection: 'D21.3',
      },
      {
        id: 'D21_4_duree',
        firestorePath: 'vendorDeclaration.d21.dureeEntentes',
        labelFr: 'Durée habituelle des ententes',
        labelEn: 'Durée habituelle des ententes',
        fieldType: 'checkbox_group',
        subSection: 'D21.4',
      },
      {
        id: 'Texte111',
        firestorePath: 'vendorDeclaration.d21.dureeEntentesAutre',
        labelFr: 'Autre durée (préciser)',
        labelEn: 'Autre durée (préciser)',
        fieldType: 'text',
        subSection: 'D21.4',
      },
      {
        id: 'D21_5_question',
        firestorePath: 'vendorDeclaration.d21.dossiersTAL',
        labelFr: 'Dossiers en cours au Tribunal administratif du logement impliquant la résidence?',
        labelEn: 'Dossiers en cours au Tribunal administratif du logement impliquant la résidence?',
        fieldType: 'yesno',
        subSection: 'D21.5',
      },
      {
        id: 'Texte112',
        firestorePath: 'vendorDeclaration.d21.dossiersTALDetails',
        labelFr: 'Si oui, résumer la nature et l\'état des dossiers',
        labelEn: 'Si oui, résumer la nature et l\'état des dossiers',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D21.5',
      },
      {
        id: 'D21_6_plaintes',
        firestorePath: 'vendorDeclaration.d21.plaintesFormelles',
        labelFr: 'Plaintes formelles de résidents ou de familles auprès de',
        labelEn: 'Plaintes formelles de résidents ou de familles auprès de',
        fieldType: 'checkbox_group',
        subSection: 'D21.6',
      },
      {
        id: 'Texte113',
        firestorePath: 'vendorDeclaration.d21.plaintesAutrePreciser',
        labelFr: 'Autre organisme (préciser)',
        labelEn: 'Autre organisme (préciser)',
        fieldType: 'text',
        subSection: 'D21.6',
      },
      {
        id: 'Texte114',
        firestorePath: 'vendorDeclaration.d21.plaintesResume',
        labelFr: 'Pour tout « Oui », donner un bref résumé',
        labelEn: 'Pour tout « Oui », donner un bref résumé',
        fieldType: 'textarea',
        subSection: 'D21.6',
      },
    ],
  },
  {
    id: 'D22',
    titleFr: 'RESSOURCES HUMAINES ET ORGANISATION DES SOINS',
    titleEn: 'RESSOURCES HUMAINES ET ORGANISATION DES SOINS',
    category: 'rpa',
    questions: [
      {
        id: 'Texte115',
        firestorePath: 'vendorDeclaration.d22.etcDirection',
        labelFr: 'Direction / gestion (ETC)',
        labelEn: 'Direction / gestion (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'Texte116',
        firestorePath: 'vendorDeclaration.d22.etcInfirmieres',
        labelFr: 'Inf. / inf. aux. (ETC)',
        labelEn: 'Inf. / inf. aux. (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'Texte117',
        firestorePath: 'vendorDeclaration.d22.etcPAB',
        labelFr: 'PAB / préposés (ETC)',
        labelEn: 'PAB / préposés (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'Texte118',
        firestorePath: 'vendorDeclaration.d22.etcCuisine',
        labelFr: 'Cuisine (ETC)',
        labelEn: 'Cuisine (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'Texte119',
        firestorePath: 'vendorDeclaration.d22.etcEntretien',
        labelFr: 'Entretien ménager (ETC)',
        labelEn: 'Entretien ménager (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'Texte120',
        firestorePath: 'vendorDeclaration.d22.etcAdmin',
        labelFr: 'Administration / accueil (ETC)',
        labelEn: 'Administration / accueil (ETC)',
        fieldType: 'number',
        subSection: 'D22.1',
      },
      {
        id: 'D22_2_question',
        firestorePath: 'vendorDeclaration.d22.personnel24h',
        labelFr: 'Présence de personnel sur place 24/7?',
        labelEn: 'Présence de personnel sur place 24/7?',
        fieldType: 'yesno',
        subSection: 'D22.2',
      },
      {
        id: 'D22_2_infirmiere',
        firestorePath: 'vendorDeclaration.d22.presenceInfirmiere',
        labelFr: 'Présence d\'une infirmière ou autre professionnel sur place',
        labelEn: 'Présence d\'une infirmière ou autre professionnel sur place',
        fieldType: 'checkbox_group',
        subSection: 'D22.2',
      },
      {
        id: 'D22_3_question',
        firestorePath: 'vendorDeclaration.d22.conventionsCollectives',
        labelFr: 'Conventions collectives en vigueur?',
        labelEn: 'Conventions collectives en vigueur?',
        fieldType: 'yesno',
        subSection: 'D22.3',
      },
      {
        id: 'Texte121',
        firestorePath: 'vendorDeclaration.d22.conventionsDetails',
        labelFr: 'Si oui, avec quel syndicat et jusqu\'à quelle échéance?',
        labelEn: 'Si oui, avec quel syndicat et jusqu\'à quelle échéance?',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D22.3',
      },
      {
        id: 'D22_4a_question',
        firestorePath: 'vendorDeclaration.d22.reclamationsCNESST',
        labelFr: 'Réclamations majeures à la CNESST (5 dernières années)?',
        labelEn: 'Réclamations majeures à la CNESST (5 dernières années)?',
        fieldType: 'yesno',
        subSection: 'D22.4a',
      },
      {
        id: 'D22_4b_question',
        firestorePath: 'vendorDeclaration.d22.enquetesHarcelement',
        labelFr: 'Enquêtes pour harcèlement psychologique ou sexuel?',
        labelEn: 'Enquêtes pour harcèlement psychologique ou sexuel?',
        fieldType: 'yesno',
        subSection: 'D22.4b',
      },
      {
        id: 'D22_4c_question',
        firestorePath: 'vendorDeclaration.d22.litigesGriefs',
        labelFr: 'Litiges judiciaires ou griefs importants?',
        labelEn: 'Litiges judiciaires ou griefs importants?',
        fieldType: 'yesno',
        subSection: 'D22.4c',
      },
      {
        id: 'Texte122',
        firestorePath: 'vendorDeclaration.d22.evenementsRHResume',
        labelFr: 'Pour tout « Oui », résumer sans nommer de personnes',
        labelEn: 'Pour tout « Oui », résumer sans nommer de personnes',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D22.4',
      },
    ],
  },
  {
    id: 'D23',
    titleFr: 'ASPECTS FINANCIERS LIÉS À L\'EXPLOITATION RPA (APERÇU)',
    titleEn: 'ASPECTS FINANCIERS LIÉS À L\'EXPLOITATION RPA (APERÇU)',
    category: 'rpa',
    questions: [
      {
        id: 'Texte123',
        firestorePath: 'vendorDeclaration.d23.dateFinExercice',
        labelFr: 'Date de fin d\'exercice financier',
        labelEn: 'Date de fin d\'exercice financier',
        fieldType: 'date',
        subSection: 'D23.1',
      },
      {
        id: 'Texte124',
        firestorePath: 'vendorDeclaration.d23.revenusBruts',
        labelFr: 'Revenus bruts totaux (approx.)',
        labelEn: 'Revenus bruts totaux (approx.)',
        fieldType: 'currency',
        subSection: 'D23.1',
      },
      {
        id: 'Texte125',
        firestorePath: 'vendorDeclaration.d23.tauxOccupationBudgete',
        labelFr: 'Taux d\'occupation budgété (%)',
        labelEn: 'Taux d\'occupation budgété (%)',
        fieldType: 'percent',
        subSection: 'D23.1',
      },
      {
        id: 'Texte126',
        firestorePath: 'vendorDeclaration.d23.programmesSubventions',
        labelFr: 'Programmes ou subventions (SHQ ou autres) - nature et montant approximatif',
        labelEn: 'Programmes ou subventions (SHQ ou autres) - nature et montant approximatif',
        fieldType: 'textarea',
        subSection: 'D23.2',
      },
      {
        id: 'Texte127',
        firestorePath: 'vendorDeclaration.d23.contratsServices',
        labelFr: 'Contrats de services essentiels (pharmacie, buanderie, sécurité, entretien gicleurs, etc.) - fournisseur, échéance, clauses de résiliation',
        labelEn: 'Contrats de services essentiels (pharmacie, buanderie, sécurité, entretien gicleurs, etc.) - fournisseur, échéance, clauses de résiliation',
        fieldType: 'textarea',
        subSection: 'D23.3',
      },
      {
        id: 'Texte128',
        firestorePath: 'vendorDeclaration.d23.financementParticulier',
        labelFr: 'Financement particulier lié à la RPA - institution financière, type de prêt, échéance, clauses pouvant affecter une vente',
        labelEn: 'Financement particulier lié à la RPA - institution financière, type de prêt, échéance, clauses pouvant affecter une vente',
        fieldType: 'textarea',
        subSection: 'D23.4',
      },
    ],
  },
  {
    id: 'D24',
    titleFr: 'ENVIRONNEMENT, VOISINAGE ET RISQUES SPÉCIFIQUES',
    titleEn: 'ENVIRONNEMENT, VOISINAGE ET RISQUES SPÉCIFIQUES',
    category: 'rpa',
    questions: [
      {
        id: 'Texte129',
        firestorePath: 'vendorDeclaration.d24.utilisationAnterieure',
        labelFr: 'Utilisation antérieure connue du site (garage, industriel, agricole, etc.)',
        labelEn: 'Utilisation antérieure connue du site (garage, industriel, agricole, etc.)',
        fieldType: 'textarea',
        subSection: 'D24.1',
      },
      {
        id: 'D24_2_question',
        firestorePath: 'vendorDeclaration.d24.etudesEnvironnementales',
        labelFr: 'Études environnementales (Phase I, II) déjà réalisées?',
        labelEn: 'Études environnementales (Phase I, II) déjà réalisées?',
        fieldType: 'yesno',
        subSection: 'D24.2',
      },
      {
        id: 'Texte130',
        firestorePath: 'vendorDeclaration.d24.etudesDetails',
        labelFr: 'Si oui, année et grandes lignes des conclusions',
        labelEn: 'Si oui, année et grandes lignes des conclusions',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D24.2',
      },
      {
        id: 'Texte131',
        firestorePath: 'vendorDeclaration.d24.nuisances',
        labelFr: 'Nuisances particulières pour une clientèle âgée (bruit, odeurs, circulation, voisinage)',
        labelEn: 'Nuisances particulières pour une clientèle âgée (bruit, odeurs, circulation, voisinage)',
        fieldType: 'textarea',
        subSection: 'D24.3',
      },
      {
        id: 'Texte132',
        firestorePath: 'vendorDeclaration.d24.autresElements',
        labelFr: 'Tout autre élément connu pouvant influencer la sécurité, le bien-être ou l\'attractivité de la RPA',
        labelEn: 'Tout autre élément connu pouvant influencer la sécurité, le bien-être ou l\'attractivité de la RPA',
        fieldType: 'textarea',
        subSection: 'D24.4',
      },
    ],
  },
  {
    id: 'D25',
    titleFr: 'COMMENTAIRES ET DÉCLARATIONS COMPLÉMENTAIRES',
    titleEn: 'COMMENTAIRES ET DÉCLARATIONS COMPLÉMENTAIRES',
    category: 'rpa',
    sectionOptional: true,
    questions: [
      {
        id: 'Texte133',
        firestorePath: 'vendorDeclaration.d25.commentaires',
        labelFr: 'Utiliser cette section pour préciser une réponse précédente ou signaler tout élément particulier lié à l\'exploitation de la résidence, à la clientèle, aux ressources ou à l\'environnement',
        labelEn: 'Utiliser cette section pour préciser une réponse précédente ou signaler tout élément particulier lié à l\'exploitation de la résidence, à la clientèle, aux ressources ou à l\'environnement',
        fieldType: 'textarea',
        optional: true,
        subSection: 'D25.1',
      },
    ],
  },
];

export const ALL_DECLARATION_QUESTION_IDS: string[] = DECLARATION_SECTIONS.flatMap(
  (s) => s.questions.map((q) => q.id)
);

export const DECLARATION_REQUIRED_QUESTION_IDS: string[] = DECLARATION_SECTIONS.flatMap(
  (s) => s.questions.filter((q) => !q.optional).map((q) => q.id)
);